import type { Metadata } from "next";

import "./globals.css";
import Header from "@/components/header/Header";

import { ClerkProvider } from "@clerk/nextjs";
import Footer from "@/components/footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="font-poppins antialiased ">
          <div className="flex flex-col min-h-screen">
            <Header />
            <main > {children}</main>
            <Footer />
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
